### ISSUE TITLE
Problem compiling from source

### ISSUE THREAD

**Issue by farooqkz** [GiviMAD/rustpotter-cli#11]
When I try to install it using `cargo install`, I get this error for `3.0.0` and `3.0.1`:

```
error[E0599]: no function or associated item named `new` found for struct `SGD` in the current scope
```

The error is from `/rustpotter-3.0.1/src/wakewords/nn/wakeword_model_train.rs:196:31`

**Comment by GiviMAD** [comment]
Sorry, one dependency introduced a breaking change in a minor release, so those versions seem to be broken, also for the library. I don't know if there is a way to force a version when installing with cargo.

Version 3.0.2 is fixed, I'm able to install it using cargo.

Thank you for raising the issue.
