### ISSUE TITLE
Add an example on how the labels should be

### ISSUE THREAD

**Issue by farooqkz** [GiviMAD/rustpotter-cli#12]
Hello. I think an example can make it easier for people to understand how they should prepare it.

**Comment by GiviMAD** [comment]
Would you be able to take a look? https://github.com/GiviMAD/rustpotter-cli/pull/13/files

**Comment by farooqkz** [comment]
> Would you be able to take a look? https://github.com/GiviMAD/rustpotter-cli/pull/13/files

Nice!
