### ISSUE TITLE
Error with spot command

### ISSUE THREAD

**Issue by adamjleonard** [GiviMAD/rustpotter-cli#4]
When attempting to run the spot command I am getting the following error

thread 'main' panicked at 'Command spot: Short option names must be unique for each argument, but '-g' is in use by both 'gain_normalizer' and 'gain_ref'', src/github.com-1ecc6299db9ec823/clap-4.1.8/src/builder/debug_asserts.rs:115:17

**Comment by GiviMAD** [comment]
Thank you for raising the issue
