### ISSUE TITLE
cpal_alsa_in panicked error

### ISSUE THREAD

**Issue by Nortonko** [GiviMAD/rustpotter-cli#5]
Hi,
I try this client. However, I still get this error:
``thread 'cpal_alsa_in' panicked at 'called `Result::unwrap()` on an `Err` value: Wrong number of frames 666 in input channel 0, expected 1323', /code/vendor/rustpotter/src/internal/encoder.rs:81:18
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
``
I tried it on several platforms - amd64 (LinuxMint), raspbbery PI3 (raspbian) and orangePI zero2 (ubuntu), the error is the same everywhere. Can you please advise me what the problem is?

**Comment by GiviMAD** [comment]
Hi, thank you for reporting it.
<s>Seems like there is a bug on the the library re-sampler configuration when using multichannel audio.</s> I'll try to fix it today.

**Comment by GiviMAD** [comment]
<s>Will you be able to share with me the "Input device config:..." line from your log?</s>
No worries I was able to reproduce it.

**Comment by Nortonko** [comment]
Hi, thanks for your effort. although it may not be necessary anymore, i am sending the log. I hope the correct one:
-rustpotter-cli spot -i 15 hey_pocitac.rpw
-Spotting using models: ["hey_pocitac.rpw"]!
-Input device: hw:CARD=Y02,DEV=0
-Input device config: SupportedStreamConfig { channels: 2, sample_rate: SampleRate(44100), buffer_size: Range { min: 90, max: 262144 }, sample_format: I16 }
-Begin recording...
-Press 'Ctrl + c' to stop.
-thread 'cpal_alsa_in' panicked at 'called `Result::unwrap()` on an `Err` value: Wrong number of frames 662 in input channel 0, expected 1323', /code/vendor/rustpotter/src/internal/encoder.rs:81:18
-note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by GiviMAD** [comment]
Seems to be fixed https://github.com/GiviMAD/rustpotter-cli/releases/tag/v2.0.2, thanks again for reporting it!
