### ISSUE TITLE
How to start

### ISSUE THREAD

**Issue by buguser1234** [GiviMAD/rustpotter-cli#7]
I have rustpotter installed in Openhab with VOSK. How do you activate it and how do you install rustpotter-cli?

**Comment by GiviMAD** [comment]
Hi,

This is not directly related to the openHAB add-on, but you can use it to record wav files and generate rustpotter wakeword files that you can use in other platforms, like the openHAB add-on which uses the rustpotter java wrapper.

Please use the openHAB forum if you have more questions related to it.

To install this project you can use the binaries from the release page or build the project your self.

BR
