### ISSUE TITLE
Is there any documentation

### ISSUE THREAD

**Issue by buguser1234** [GiviMAD/rustpotter-cli#8]
How do you invoke this> Are there any examples on how to use this with Openhab or VOSK?

**Comment by GiviMAD** [comment]
Hi,

There is no direct relation between this project and the openHAB add-on, you can use it to generate wakewords for rustpotter.

Please take in consideration that openHAB 3.4.x uses rustpotter v1, incompatible with the v2 wakewords.

I have the intention to allow connect this cli to openHAB through the rustpotter add-on to act as a remote keyword spotter but I'm waiting for the review of this PR https://github.com/openhab/openhab-core/pull/3564.

And no, I think there is no documentation at the moment about how to enable the dialog processing on openHAB, I'll try to write a post about it when I have a moment and ping it here. After this PR https://github.com/openhab/openhab-core/pull/3459 gets reviewed and merged, it should be easy to manage the dialog creation but it could be done either way.

BR

**Comment by GiviMAD** [comment]
The readme has been improved and updated with the latests version features.

I didn't have time to publish the openHAB post with and example of how to setup things, almost written but I have to give it a final review. I hope I have time to do it in the following days.

BR

**Comment by buguser1234** [comment]
Thanks. Martin

Sent with [Proton Mail](https://proton.me/) secure email.

------- Original Message -------

**Comment by GiviMAD** [comment]
You can find here a summary of how you can enable dialog processing https://community.openhab.org/t/dialog-processing-with-the-pulseaudiobinding/148191 in openHAB 4, hope it helps!
